project:
  type: website
  output-dir: docs

website:
  title: "Horacio Lopez-Nicora"
  navbar:
    left:
      - href: Home.qmd
        text: Home
        icon: house
      - about.qmd
      - research.qmd
    sidebar:
    tools:
      - icon: github
        href: https://github.com/Lopez-Nicora
  
        
  page-footer: 
    background: light
    left: Copyright 2023, Horacio Lopez-Nicora, Ph.D.
    right: This website is built with {{< fa heart title="a heart" >}} and [Quarto](https://quarto.org/)

format:
  html:
    theme: flatly
    fontsize: 1.1em
    linestretch: 1.7
    css: styles.css
    toc: true




